### ISSUE TITLE
Search not finding all packages

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#103]
Hey,

for some reason, the search in WoltLab is not finding all packages from this package server.
While the search doesn't find the package, the update search does.

What could be causing the issue?

![vivaldi_2022-04-17_01-37-02](https://user-images.githubusercontent.com/5961995/163694388-68dda956-7fe7-4523-8daa-10e8b2390473.png)
![2022-04-17_01-39-31](https://user-images.githubusercontent.com/5961995/163694437-dae51705-d85a-4c6f-9c2f-1eb9a28a4544.png)

**Comment by TimWolla** [comment]
1. Your search query is not appropriate to find the package in question (e.g. due to localization).
2. The package is not actually available (`accessible="false"`) and thus not offered.

In any case this is not a bug in the package server, because it serves packages correctly. If anything it would be a bug in WoltLab Suite, but I also doubt that.

**Comment by Sir-Will** [comment]
I did manually run the query, and it finds the package in the database, so I added a bunch of debug messages to find out where it gets skipped.
It got skipped here: https://github.com/WoltLab/WCF/blob/5.4/wcfsetup/install/files/lib/data/package/update/PackageUpdateAction.class.php#L493
because of the missing requirement from #104.

Sucks that there is no proper feedback.
