### ISSUE TITLE
Fehler bei der Docker benutzung

### ISSUE THREAD

**Issue by HerrTxbias** [wbbaddons/Tims-PackageServer#18]
Hey,

ich benutze die Docker version von dem Package Server, ich bekomme auch alle Packages angezeigt, jedoch wenn Woltlab versucht, die Pakete zu laden, kommt nur ein Fehler:
`Beim letzten Verbindungsversuch trat folgender Fehler auf:
Die Paketliste konnte nicht abgerufen werden (0)`

Irgendeine Idee?

**Comment by TimWolla** [comment]
> ich benutze die Docker version von dem Package Server, ich bekomme auch alle Packages angezeigt,

So clearly the package server is working correctly.

> Beim letzten Verbindungsversuch trat folgender Fehler auf: Die Paketliste konnte nicht abgerufen werden (0)

Error Code 0 indicates that WoltLab Suite was unable to establish a TCP connection. This could be due to a firewall, bad DNS, bad routing, bad TLS certificates, or anything else. Check your PHP logs and possibly have a look at what PHP is doing using strace or tcpdump.
